In [1]:
#Task 1
#import pandas
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
import numpy as np
import os
import sklearn


##import inforamtion from Kaggle 
CCLoan = pd.read_csv(r'D:\springboard\DataScienceGuidedCapstone\Unit7\DataCapstoneProject2\ccFraudDefault\application_data.csv',header=0)

In [2]:
#Task 2
#rename certian column to be more readable
CCLoan.rename(columns={'SK_ID_CURR':'CLIENTID','TARGET':'LATE_PAYMENT'},inplace = True)


Task 5

In [3]:
#Task 5.1
#take a look what is 25%, 50% and 75% of credit of loan

np.percentile(CCLoan['AMT_CREDIT'],[25,50,75])

array([270000., 513531., 808650.])

In [4]:
#Task 5.2
#take a look what is 25%, 50% and 75% of credit of loan

np.percentile(CCLoan['AMT_CREDIT'],[25,50,75])

array([270000., 513531., 808650.])

In [5]:
#Task 5.3
#take a look what is 25%, 50% and 75% of credit of loan

np.percentile(CCLoan['AMT_CREDIT'],[25,50,75])

array([270000., 513531., 808650.])

In [ ]:
sns.pairplot(CCLoan)

#Task 10
it just runs and didnt graphy
#test graph swarm plot
sns.swarmplot(y='LATE_PAYMENT', x ='NAME_CONTRACT_TYPE', data=CCLoan)
plt.xlabel('Type of Loan')
plt.ylabel('Late Payment')
plt.show()